services:
  db:
    image: "mysql:8.4"
    environment:
      - MYSQL_ROOT_PASSWORD=07Momo05
    volumes:
      - db_data:/var/lib/mysql
  pma:
    image: phpmyadmin
    ports:
      - "8080:80"
  app:
    image: shitty_app_with_db:1.0
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./src:/app/src"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=07Momo05
      - DB_NAME=db
      - DB_PORT=3306
      - PORT=3000
volumes:
  db_data: